title: Cyber Guardian
description: ค้นหาความตื่นเต้น....ไปกับ.....ไซไฟ AI ปัชญา จิตวิทยา ความเชื่อ พวกเขาจะทำอย่างไร...ถ้า AI มันควบคุมเรา

remote_theme: just-the-docs/just-the-docs
url: https://xxxxxdeveloper.github.io/Cyber-Guardian-novel

head:
  - '<link href="https://fonts.googleapis.com/css2?family=Mitr&display=swap" rel="stylesheet">'


just_the_docs:
  custom_css:
    - assets/css/custom.css




