title: Cyber Guardian
description: ค้นหาความตื่นเต้น....ไปกับ.....ไซไฟ AI ปัชญา จิตวิทยา ความเชื่อ พวกเขาจะทำอย่างไร...ถ้า AI มันควบคุมเรา

theme: jekyll-theme-midnight
url: "https://xxxxxdeveloper.github.io"
baseurl: "/Cyber-Guardian-novel"

