title: Cyber Guardian Novel
description: นิยายไซไฟ AI และจิตวิทยาในโลกอนาคต
theme: just-the-docs

url: https://xxxxxdeveloper.github.io/Cyber-Guardian

aux_links:
  GitHub Repository: https://github.com/xxxxxdeveloper/Cyber-Guardian-public
