title: Cyber Guardian
description: ค้นหาความตื่นเต้น....ไปกับ.....ไซไฟ AI ปัชญา จิตวิทยา ความเชื่อ พวกเขาจะทำอย่างไร...ถ้า AI มันควบคุมเรา

remote_theme: xxxxxdeveloper/just-the-docs
url: "https://xxxxxdeveloper.github.io"

# -------------------------------------------------------------------
# !!! เพิ่มบรรทัดนี้เข้าไป !!!
baseurl: "/Cyber-Guardian-novel"
# -------------------------------------------------------------------

# For just-the-docs theme customization
head:
  - '<link href="https://fonts.googleapis.com/css2?family=Mitr&display=swap" rel="stylesheet">'

just_the_docs:
  custom_css:
    - assets/css/custom.css

