remote_theme: just-the-docs/just-the-docs

head:
  - '<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">'

just_the_docs:
  custom_css:
    - assets/css/custom.css

plugins:
  - jekyll-default-layout





